spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/db_order
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: pass123

springdoc:
  swagger-ui.path: /swagger-ui-custom.html

tracing:
  url: http://localhost:4318/v1/traces

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'